import type { MetaFunction } from "react-router";
import LegalPage from "../components/legal/LegalPage";

export const meta: MetaFunction = () => [
  { title: "Privacy Policy | Fegig Technologies" },
  {
    name: "description",
    content:
      "How Fegig Technologies Limited collects, uses, protects, and retains personal data.",
  },
];

export default function PrivacyPage() {
  return (
    <LegalPage
      label="Data practice / L02"
      title="Privacy Policy"
      summary="A plain-language account of the personal data we receive, why we use it, and the choices available to you."
    >
      <p>
        Fegig Technologies Limited (“Fegig”, “we”, “us”, or “our”) is responsible
        for the personal data described in this policy. This notice applies to
        visitors to our website, people who contact us, prospective clients, and
        client representatives.
      </p>

      <h2>1. Information we receive</h2>
      <h3>Information you provide</h3>
      <p>
        We may receive your name, email address, phone number, company, project
        details, documents, links, messages, billing information, and other
        information you choose to send by email or during a business
        conversation.
      </p>
      <h3>Information generated by website use</h3>
      <p>
        Our hosting and security providers may process basic technical records
        such as IP address, browser and device information, request time,
        requested page, referring page, error events, and security signals.
        Embedded support or communication tools may also process information
        needed to provide that feature. We do not use this website to make
        solely automated decisions with legal or similarly significant effects.
      </p>

      <h2>2. Why we use personal data</h2>
      <ul>
        <li>to respond to an enquiry and assess a possible engagement;</li>
        <li>to prepare proposals and perform a contract;</li>
        <li>to manage client relationships, delivery, support, and billing;</li>
        <li>to secure, maintain, troubleshoot, and improve our website and services;</li>
        <li>to keep business, tax, and compliance records; and</li>
        <li>to establish, exercise, or defend legal rights.</li>
      </ul>

      <h2>3. Lawful bases</h2>
      <p>
        Depending on the context, we process personal data because it is needed
        to take steps at your request before a contract or to perform a
        contract; because we have a legitimate interest in operating and
        protecting our business; because we must meet a legal obligation; or
        because you have given consent. Where processing relies on consent, you
        may withdraw it without affecting earlier lawful processing.
      </p>

      <h2>4. When information is shared</h2>
      <p>
        We may share only what is reasonably necessary with service providers
        supporting hosting, communication, collaboration, payment, accounting,
        security, or professional advice. We may also disclose information when
        required by law, to protect rights and safety, or as part of a genuine
        corporate transaction. We do not sell personal data.
      </p>

      <h2>5. International processing</h2>
      <p>
        Some providers or project collaborators may process information outside
        Nigeria. Where a transfer requires protection, we use a lawful transfer
        mechanism and reasonable contractual, organisational, or technical
        safeguards appropriate to the information and destination.
      </p>

      <h2>6. Retention</h2>
      <p>
        We keep personal data only for as long as it is reasonably needed for
        the purpose collected, including contractual, security, tax,
        accounting, and legal requirements. General project enquiries are
        normally reviewed for deletion after 24 months if no engagement
        follows. Client and transaction records may be retained longer where
        required by law or needed to establish contractual history.
      </p>

      <h2>7. Security</h2>
      <p>
        We use proportionate access controls, reputable service providers,
        software maintenance, and operational safeguards designed to protect
        personal data. No internet transmission or storage system can be
        guaranteed completely secure, so please avoid sending unnecessary
        sensitive information through an initial enquiry.
      </p>

      <h2>8. Your rights</h2>
      <p>
        Subject to the Nigeria Data Protection Act 2023 and other applicable
        law, you may have rights to be informed, request access, correct
        inaccurate data, request deletion or restriction, object to certain
        processing, withdraw consent, request portability, and complain to the
        Nigeria Data Protection Commission.
      </p>
      <p>
        To make a request, email{" "}
        <a href="mailto:messageme@codewithfegig.com">
          messageme@codewithfegig.com
        </a>
        . We may need enough information to verify your identity and locate the
        relevant records. You can also learn about data-subject rights from the{" "}
        <a
          href="https://ndpc.gov.ng/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Nigeria Data Protection Commission
        </a>
        .
      </p>

      <h2>9. Children</h2>
      <p>
        This company website is directed to business audiences and is not
        intended to collect personal data directly from children. If you believe
        a child has provided personal data through this site, please contact us
        so we can review and take appropriate action.
      </p>

      <h2>10. External links and changes</h2>
      <p>
        External websites and services have their own privacy practices. We may
        update this policy when our processing or legal obligations change. The
        effective date above identifies the current version.
      </p>
    </LegalPage>
  );
}
